# Generated by Django 5.1.2 on 2025-01-17 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField(verbose_name='本')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('language', '言語'), ('other', 'その他')], max_length=100)),
                ('thumbnail', models.ImageField(upload_to='')),
                ('about', models.TextField()),
                ('b_created_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chapters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_id', models.IntegerField(verbose_name='章')),
                ('chapter_name', models.CharField(max_length=100)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.books', verbose_name='本')),
            ],
        ),
        migrations.CreateModel(
            name='Contents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.IntegerField(verbose_name='目次')),
                ('content_name', models.CharField(max_length=100)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.chapters', verbose_name='章')),
            ],
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=100)),
                ('page_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('contents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.contents', verbose_name='目次')),
            ],
        ),
    ]
