# Generated by Django 5.1.2 on 2025-01-22 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pages',
            name='page_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
