# Generated by Django 5.1.2 on 2025-01-24 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_pages_text_alter_pages_page_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapters',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='myapp.books', verbose_name='本'),
        ),
        migrations.AlterField(
            model_name='contents',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='myapp.chapters', verbose_name='章'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='contents',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='myapp.contents', verbose_name='目次'),
        ),
    ]
