# Generated by Django 5.1.2 on 2025-01-24 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_chapters_book_alter_contents_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='chapters',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='myapp.books'),
        ),
        migrations.AlterField(
            model_name='chapters',
            name='chapter_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contents',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='myapp.chapters'),
        ),
        migrations.AlterField(
            model_name='contents',
            name='content_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pages',
            name='contents',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='myapp.contents'),
        ),
    ]
