# Generated by Django 5.1.2 on 2025-01-24 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_books_book_id_alter_chapters_book_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contents',
            old_name='book',
            new_name='chapter',
        ),
    ]
